[package]
name = "spectrogram"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10"
error-iter = "0.4"
libm = "0.2"
log = "0.4"
pixels = "0.13"
plotters = "0.3.4"
winit = "0.28"
winit_input_helper = "0.14"

[dependencies.microfft]
version = "0.5"
features = ["std"]
